---
title: "omicron_case"
output: html_document
---
#Taking difference in growth rate in omicron (BA.1) vs its corresponding clade 
#

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(nnet)
library(MASS)
library(MNLpred)
```


#read in clade and PANGO lineage counts accessed June 5th  
```{r}
cladenum <- read_tsv("~/growthadvantagecompare/sequences_static/global-2.tsv") %>% rename(variant = clade)

#https://data.nextstrain.org/files/workflows/forecasts-ncov/gisaid/pango_lineages/global.tsv.gz

pangonum <- read_tsv("~/growthadvantagecompare/sequences_static/global.tsv") %>% rename(variant = clade)

#https://data.nextstrain.org/files/workflows/forecasts-ncov/gisaid/nextstrain_clades/global.tsv.gz

https://ncov-clades-schema.vercel.app
```


#Plot counts of BA.1 (Omicron 1) vs clade 21K in USA
```{r}
#restrict data to first appearance of clade (because clade is assigned when growth of pango lineage is high)

usa_pBA1 <- pangonum %>% filter(location == "USA", variant == c("BA.1")) %>% mutate("Unit"= "Pangolin BA.1")

usa_c21K <- cladenum %>% filter(location == "USA", variant == "21K")  %>% mutate("Unit"= "Clade 21K")

mindate <- min(usa_c21K$date + 500) 
maxdate <- mindate + 730

usa_c21kpBa1 <- bind_rows(usa_c21K, usa_pBA1) %>% 
  filter(date < maxdate & date > mindate)


ggplot(usa_c21kpBa1, aes(x = date, y = sequences, fill = Unit)) + 
  geom_col() +
  labs(title = "Pango lineage and Clade Seq Volume") +
  theme_minimal()


```
#Plot all sequences volume by day (should be the same)
```{r}
#tot n per day

cladetotn_usa <- cladenum %>% filter(location == "USA") %>% 
  group_by(date) %>% summarise(totn = sum(sequences)) %>% 
  mutate("source" = "Clade")

pangototn_usa <- pangonum %>% filter(location == "USA") %>% 
  group_by(date) %>% summarise(totn = sum(sequences)) %>% 
  mutate("source" = "Pangolin")


ggplot() +
  geom_col(data = cladetotn_usa %>% filter(source == "Clade"),
           aes(x = date, y = totn, fill = source), alpha = 0.8) +
  geom_line(data = pangototn_usa %>% filter(source == "Pangolin"),
            aes(x = date, y = totn, color = source), size = 1.5, opacity = .3) +
  scale_fill_manual(values = c("Clade" = "coral")) +
  scale_color_manual(values = c("Pangolin" = "steelblue")) +
  labs(
    title = "Total Sequences by Unit Over Time (Ensure consistency)",
    x = "Date",
    y = "Total Sequences",
    fill = "Source",
    color = "Source"
  ) +
  theme_minimal()

```
#Plot proportions of clade and pangos in time frame
```{r}

#New max ad min date, filter to where first emerged pango (BA.1) prop above 5% and add a year 

pangoprops_usa <- left_join(pangototn_usa, pangonum %>% filter(location == "USA"), by = "date") %>% 
  mutate(pangoprop = sequences/totn)

cladeprops_usa <- left_join(cladetotn_usa, cladenum %>% filter(location == "USA"), by = "date") %>% 
  mutate(cladeprop = sequences/totn)

mindate <- pangoprops_usa %>% filter(variant == "BA.1", pangoprop > .1) %>% 
summarise(date = min(date)) %>% 
pull(.)

maxdate <- mindate + 365


ggplot(data = cladeprops_usa %>% filter(variant == c("21K", "21L", "22C"), date > mindate & date < maxdate), aes(x = date, y = cladeprop, color = variant)) +
  geom_point(alpha = 0.7) +
  labs(
    title = "Clade Proportions Over Time",
    x = "Date",
    y = "Proportion",
    color = "Variant"
  ) +
  theme_minimal()

#filtered
ggplot(data = pangoprops_usa %>% filter(variant == c("BA.1", "BA.2", "BA.2.12.1"), date > mindate & date < maxdate), aes(x = date, y = pangoprop, color = variant)) +
  geom_point(alpha = 0.7) +
  labs(
    title = "Pango Proportions Over Time",
    x = "Date",
    y = "Proportion",
    color = "Variant"
  ) +
  theme_minimal()





```
#For clades
```{r}
set.seed(69)

#make date an integer and ungroup observations, makes a lot of observations so slice at 80k
mlr_cladeprops_usa <- cladeprops_usa %>%
  filter(date >= mindate & date <= maxdate) %>%
  mutate(time = as.integer(date - mindate)) %>%
  uncount(sequences) %>%
  slice_sample(n = 80000)


gc()

mod1 <- multinom(variant ~ time,
                 data = mlr_cladeprops_usa,
                 Hess = TRUE,
                 maxit = 1000)
gc()

#Predict with mnlpred
pred1_mnlpred <- mnl_pred_ova(model = mod1,
                      data = mlr_cladeprops_usa,
                      x = "time",
                      by = 6,
                      seed = 69,
                      nsim = 5, # faster
                      probs = c(0.005, 0.995))
gc()



#predict with predict

datetime <- data.frame(time = mlr_cladeprops_usa$time,
                       date = mlr_cladeprops_usa$date) %>% arrange(time) %>% distinct()

  
pred1_pred <- as.data.frame(predict(mod1, newdata = datetime, type = "probs")) %>% 
 cbind(datetime)%>%
  select(-"time") %>% 
   pivot_longer(
     cols = -date,
     names_to = "variant",
     values_to = "mean"
    )

library(dplyr)
library(tidyr)


pred1_pred <- predict(mod1, newdata = datetime, type = "probs") %>%
  as.data.frame() %>%
  bind_cols(datetime) %>%
  dplyr::select(-time) %>%
  pivot_longer(
    cols = -date,
    names_to = "variant",
    values_to = "mean"
  )


```

#Plot clade
```{r}
cladeprops_usa_filt <- cladeprops_usa %>%
  filter(date >= mindate & date <= maxdate)

#MNLpred plot
pred1_mnlpred <- pred1_mnlpred$plotdata %>% 
  mutate(date = mindate+time)


ggplot(
  data = pred1_mnlpred,
  aes(x = date, color = variant, fill = variant)
) +  geom_line(
    aes(y = mean),
    size = 1
  ) +  geom_point(
    data = cladeprops_usa_filt,
    aes(x = date, y = cladeprop, color = variant),
    alpha = 0.4,
    inherit.aes = FALSE) +
  labs(
    title = "USA Clades vs MLR Model Fit",
    subtitle = "MNLpred: variant ~ time",
    x = "Date",
    y = "Proportion"
  ) +
  theme_minimal() +
  theme(legend.title = element_blank())


#predict plot
library(ggplot2)
library(dplyr)

ggplot(pred1_pred, aes(x = date, y = mean, color = variant)) +
  geom_line(size = 1) +
   geom_point(
    data = cladeprops_usa_filt,
    aes(x = date, y = cladeprop, color = variant),
    alpha = 0.4,
    inherit.aes = FALSE) +
   labs(
    title = "USA Clade Proportions vs MLR Model Fit",
    subtitle = "predict: variant ~ time",
    x = "Date",
    y = "Proportion"
  ) +
  theme_minimal() +
  theme(legend.title = element_blank())



```

#Clades spline edition (WIP)
```{r}


set.seed(123)

#create spline basis
splinetime <- data.frame(
  time = mlr_cladeprops_usa$time,
  date = mlr_cladeprops_usa$date,
  s1 = ns(mlr_cladeprops_usa$time, df = 2)[,1],
  s2 = ns(mlr_cladeprops_usa$time, df = 2)[,2]
) %>%
  arrange(time) %>%
  distinct()


mlr_cladeprops_usa_spline <- left_join(mlr_cladeprops_usa, splinetime, by = c("time", "date"))

mod1_spline <- multinom(
  variant ~ s1 + s2,
  data = mlr_cladeprops_usa_spline,
  Hess = TRUE,
  maxit = 1000
)

# Predict on spline time grid
mod1_spline_long <- predict(mod1_spline, newdata = splinetime, type = "probs") %>%
  as.data.frame() %>%
  bind_cols(splinetime %>% dplyr::select(date)) %>%
  pivot_longer(
    cols = -date,
    names_to = "variant",
    values_to = "mean"
  )

ggplot()+
  geom_point(data=cladeprops_usa_filt,aes(x=date,y=cladeprop,color=variant),alpha=0.4)+
  geom_line(data=mod1_spline_long,aes(x=date,y=mean,color=variant),size=1)+
  labs(title="USA Clade Proportions vs Splined MLR Model Fit",x="Date",y="Predicted Proportion",
       subtitle = "variant ~ spline 1 + spline 2"
         )+
  theme_minimal()+
  theme(legend.title=element_blank())



AIC(mod1)
AIC(mod1_spline)

BIC(mod1)
BIC(mod1_spline)


```

